### ISSUE TITLE
problem with cmake and Qt5Declarative

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/yarpviz#1]
Hi, I am trying to install yarpviz but I get an error with the cmake.
I am on Ubuntu14.04
I downladed the dependencies, including Qt5declarative, but I still have the following error in the cmake:

CMake Warning at CMakeLists.txt:27 (find_package):
   By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
   project has asked CMake to find a package configuration file provided by
   "Qt5Declarative", but CMake did not find one.

   Could not find a package configuration file provided by "Qt5Declarative"
   with any of the following names:

```
 Qt5DeclarativeConfig.cmake
 qt5declarative-config.cmake
```

   Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
   "Qt5Declarative_DIR" to a directory containing one of the above files.  If
   "Qt5Declarative" provides a separate development package or SDK, be sure it
   has been installed.

Any idea how to fix this? Thanks in advance.

**Comment by lornat75** [comment]
I had the same problem, however the code compiled fine (the warning is annoying though).

**Comment by Nicogene** [comment]
Hi @serena-ivaldi,
do you still have these cmake problems?

**Comment by Nicogene** [comment]
For now I close this issue, if the problem persists I will reopen it
