### ISSUE TITLE
yarpviz is integrated in yarp now

### ISSUE THREAD

**Issue by traversaro** [robotology/yarpviz#9]
Since https://github.com/robotology/yarp/pull/1300 yarpviz is integrated in YARP `devel`. However, the documentation does not mentioned this, and so this could be confusing for users. 
@Nicogene can you update the documentation and perhaps do a little QA announcement? Thanks!

**Comment by traversaro** [comment]
It would also be good to port some of the awesome documentaiton available here in http://www.yarp.it/devel/yarpviz.html (for example details on the compilation option of YARP that need to be enabled to get yarpviz, etc etc).

**Comment by Nicogene** [comment]
This pr [1446](https://github.com/robotology/yarp/pull/1446) imported in yarp the yarpviz documentation.
Here the QA [announcement](https://github.com/robotology/QA/issues/261)
